[package]
name = "fx-durable-ga-example-feature-engineering"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn.git", features = ["train"], default-features = false }
thiserror = "2.0.12"
regex = "1.12.2"
anyhow = "1.0.100"
approx = "0.5.1"
